[build]
  command = "npm run build"
  publish = "build"
  base = "frontend"

[[redirects]]
  from = "/api/*"
  to = "https://your-render-app-url.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200